import type { Metadata } from "next";
import { geistSans, geistMono } from "@/fonts";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import GlobalPresence from "@/components/layout/GlobalPresence";
import Navbar from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1 pt-24">{children}</main>
        <Footer />
        <GlobalPresence />
      </body>
    </html>
  );
}
